const cors = require('cors');
const authRouter = require('./routers/auth');
const  bookRouter = require('./routers/book.js');
const  userRouter = require('./routers/user');
// const  leaderBoardRouter = require('./leaderBoard.js');
// const reviewsRouter  = require('./reviews.js');
const { PORT } = require('./config');
const helmet = require('helmet');
const express = require('express');
const cookieParser = require('cookie-parser');
const app = express();
app.use(cors({ origin: true, credentials: true }));
app.use(cookieParser());
app.use(helmet());
app.use(express.json({type: ['application/json', 'text/plain']})); 
app.use(express.urlencoded({ extended: true }));
app.use('/', authRouter);
app.use('/', bookRouter);
app.use('/', userRouter);
// app.use('/', reviewsRouter);
// app.use('/', leaderBoardRouter);

app.listen(PORT, () => console.log(`Server start port - ${PORT}`));